runtime: custom
env: flex

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

env_variables:
  ASPNETCORE_ENVIRONMENT: "Development"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
